package io.github.secozzi.gradle.tasks

import io.github.secozzi.gradle.api.ContentWarning
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateManifestTask : DefaultTask() {
    @get:Input
    abstract val extensionName: Property<String>

    @get:Input
    abstract val contentWarning: Property<ContentWarning>

    @get:Input
    abstract val torrent: Property<Boolean>

    @get:Input
    abstract val extensionLib: Property<String>

    @get:Input
    abstract val qualifiedName: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val name = extensionName.get().escapeXml()
        val cls = qualifiedName.get()
        val lib = extensionLib.get()
        val cw = contentWarning.get()
        val tr = torrent.get()
        val nsfw = if (cw == ContentWarning.SAFE) "0" else "1"
        val cwValue = when (cw) {
            ContentWarning.SAFE -> "0"
            ContentWarning.MIXED -> "1"
            ContentWarning.NSFW -> "2"
        }
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        out.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by proj.plugins.extension — do not edit by hand. -->
            |<manifest xmlns:android="http://schemas.android.com/apk/res/android">
            |    <uses-feature android:name="tachiyomi.animeextension" />
            |    <application
            |        android:allowBackup="false"
            |        android:icon="@mipmap/ic_launcher"
            |        android:label="Aniyomi: $name">
            |        <meta-data android:name="tachiyomi.animeextension.class" android:value=".$cls" />
            |        <meta-data android:name="tachiyomi.animeextension.nsfw" android:value="$nsfw" />
            |        <meta-data android:name="aniyomix.name" android:value="$name" />
            |        <meta-data android:name="aniyomix.torrent" android:value="$tr" />
            |        <meta-data android:name="aniyomix.contentWarning" android:value="$cwValue" />
            |        <meta-data android:name="aniyomix.extensionLib" android:value="$lib" />
            |    </application>
            |</manifest>
            |
            """.trimMargin(),
        )
    }
}

private fun String.escapeXml() = replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;")
