name: "Batch close stale issues"

on:
  # Monthly
  schedule:
    - cron: '0 0 1 * *'
  # Manual trigger
  workflow_dispatch:
    inputs:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Close everything older than ~6 months
        days-before-issue-stale: 180
        days-before-issue-close: 0
        exempt-issue-labels: "do-not-autoclose,Meta request"
        close-issue-message: "In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose)."
        close-issue-reason: not_planned
        ascending: true
        operations-per-run: 250
