name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/scripts/**'
      - '.github/workflows/build_push.yml'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build extensions
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout master branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true

      - name: Prepare signing key
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew -p src assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: "github.repository == 'Secozzi/aniyomi-extensions'"
        with:
          name: "individual-apks"
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/source-info.json
          retention-days: 1

      - name: Clean up CI files
        if: always()
        run: rm signingkey.jks

  publish_repo:
    name: Publish repo
    needs:
      - build
    if: >-
      always() &&
      github.repository == 'Secozzi/aniyomi-extensions' &&
      needs.build.result != 'failure' &&
      needs.build.result != 'cancelled'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Download APK artifacts
        if: needs.build.result == 'success'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ~/apk-artifacts

      - name: Checkout master branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: master
          path: master

      - name: Checkout repo branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_PAT }}
          ref: repo
          path: repo

      - name: Publish and deploy repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd repo
          pip install protobuf
          python -u ../master/.github/scripts/publish-repo.py "$GITHUB_SHA"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update extensions repo"
            gh auth setup-git
            git push
            curl https://purge.jsdelivr.net/gh/Secozzi/aniyomi-extensions@repo/index.json
            curl https://purge.jsdelivr.net/gh/Secozzi/aniyomi-extensions@repo/index.pb
          else
            echo "No changes to commit"
          fi
