name: PR build check

on:
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!.github/**"
      - ".github/workflows/build_pull_request.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build extensions
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout PR
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build extensions
        run: ./gradlew -p src lintRelease
